// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfPyW5I-GmPa3dAz4FZExnxIwZXjqAo8',
    appId: '1:338796682336:web:1492d7be8fbbb34241f705',
    messagingSenderId: '338796682336',
    projectId: 'moz-nc-threads',
    authDomain: 'moz-nc-threads.firebaseapp.com',
    storageBucket: 'moz-nc-threads.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfrCtGpueqt_671hzE8vTzfGBkegJSJnY',
    appId: '1:338796682336:android:ff225083237001e141f705',
    messagingSenderId: '338796682336',
    projectId: 'moz-nc-threads',
    storageBucket: 'moz-nc-threads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB9CE0wRAKX4qabyiDZejgbCa-vMe-_To',
    appId: '1:338796682336:ios:98ab10f0a5429fb341f705',
    messagingSenderId: '338796682336',
    projectId: 'moz-nc-threads',
    storageBucket: 'moz-nc-threads.appspot.com',
    iosBundleId: 'com.example.ncFlutterThreads',
  );
}
